# Generated by Django 4.2.23 on 2026-02-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionAttempt',
            fields=[
                ('uuid', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('project', models.CharField(default='', max_length=200)),
                ('platform', models.CharField(blank=True, default='', max_length=200)),
                ('site', models.CharField(default='', max_length=200)),
                ('run_index', models.CharField(blank=True, default='', max_length=200)),
                ('run_id', models.CharField(blank=True, default='', max_length=200)),
                ('is_published', models.BooleanField()),
                ('is_test_attempt', models.BooleanField()),
                ('climb_id', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.CharField(blank=True, default='', max_length=600)),
                ('status', models.CharField(choices=[('US', 'Unstarted'), ('MD', 'Awaiting metadata checks'), ('VD', 'Awaiting validation Checks'), ('FM', 'Metadata checks fail'), ('FV', 'Validation checks fail'), ('SU', 'Success')], default='US', max_length=2)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_hash', models.CharField(max_length=200)),
                ('site_output', models.CharField(max_length=100)),
                ('projects_output', models.CharField(max_length=500)),
            ],
        ),
    ]
