FROM python:3.10-slim-bookworm

RUN apt-get update && \
    apt-get upgrade -y

COPY requirements.txt /requirements.txt
COPY requirements-test.txt /requirements-test.txt

# Install requirements from the project
RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install -r requirements-test.txt

RUN rm /requirements*

COPY agate /agate

RUN cd agate && \
    mv core/local_settings.test.py core/local_settings.py && \
    python manage.py makemigrations 

WORKDIR /agate

CMD [ "python", "manage.py", "test" ]