# This secrets file is for demonstration purposes only.
# Normally we would not be putting secrets into git.
# Secrets for setting up message config (should not be here for production)
apiVersion: v1
kind: Secret
metadata:
  name: message-config-secret
type: Opaque
stringData:
  varys_config.cfg: |
    {
        "version": "0.1",
        "profiles": {
            "test": {
                "username": "guest",
                "password": "guest",
                "amqp_url": "rabbitmq_service",
                "port": "5672",
                "use_tls": false
            }
        }
    }
---
# Django app secrets (should not be here for production)
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: "your-super-secret-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
