apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "127.0.0.1"
  CORS_ALLOWED_ORIGINS: "http://127.0.0.1:5173,http://localhost:5173"
  CSRF_TRUSTED_ORIGINS: "http://127.0.0.1:5173,http://localhost:5173"
  ONYX_DOMAIN: "http://host.containers.internal:8002"
  LIMITED_PROJECT_LIST: "mscape,synthscape"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
      - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      volumes:
        - name: message-config
          secret:
            secretName: message-config-secret
      # By running an init container, we ensure that django doesn't
      # try to perform migrations on a non-existing database
      initContainers:
        - name: wait-for-postgres
          image: postgres:13-alpine
          command:
            [
            "sh",
            "-c",
            "echo 'Waiting for Postgres...' && \
            until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER; do \
            echo 'Postgres unavailable - sleeping'; \
            sleep 1; \
            done"
            ]
          envFrom:
            - configMapRef:
                name: postgres-config
      containers:
        - name: web
          image: localhost/agate:latest
          imagePullPolicy: Never

          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret

          volumeMounts:
            - name: message-config
              mountPath: /app/varys_config.cfg
              subPath: varys_config.cfg
              readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-scheduler
  labels:
    app: django-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-scheduler
  template:
    metadata:
      labels:
        app: django-scheduler
    spec:
      volumes:
        - name: message-config
          secret:
            secretName: message-config-secret
      containers:
        - name: scheduler
          image: localhost/agate:latest
          imagePullPolicy: Never

          # This runs the scheduler, not the web server
          command: ["python", "manage.py", "runscheduler"]

          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret

          volumeMounts:
            - name: message-config
              mountPath: /app/varys_config.cfg
              subPath: varys_config.cfg
              readOnly: true
