# This secrets file is for demonstration purposes only.
# Normally we would not be putting secrets into git.
# Secrets for setting up message config (should not be here for production)
apiVersion: v1
kind: Secret
metadata:
  name: message-config-secret
  namespace: agate
type: Opaque
stringData:
  varys_config.cfg: |
    {
        "version": "0.1",
        "profiles": {
            "test": {
                "username": "guest",
                "password": "guest",
                "amqp_url": "rabbitmq",
                "port": "5672",
                "use_tls": false
            }
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: message-config-certs
  namespace: agate
type: Opaque
data:
  ca_certificate.pem: cmVwbGFjZV93aXRoX2Jhc2U2NF9lbmNvZGVkX2ZpbGUK
  client_climb-tre-rabbitmq.climb.ac.uk_certificate.pem: cmVwbGFjZV93aXRoX2Jhc2U2NF9lbmNvZGVkX2ZpbGUK
  client_climb-tre-rabbitmq.climb.ac.uk_key.pem: cmVwbGFjZV93aXRoX2Jhc2U2NF9lbmNvZGVkX2ZpbGUK
---
# Django app secrets (should not be here for production)
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: agate
type: Opaque
stringData:
  SECRET_KEY: "your-super-secret-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: agate
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
